---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      -  /home/jpinheiro/compose-configs/code-server-config:/config
      -  /home/jpinheiro/git-repos/:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
