

version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /home/jpinheiro/git-repos/docker-recipes/jellyfin/config:/config
      - /home/jpinheiro/git-repos/docker-recipes/jellyfin/cache:/cache
      - /home/jpinheiro/Videos/Movies:/media:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
